-- MySQL Script generated by MySQL Workbench
-- Tue May 26 17:25:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema animaux_refonte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema animaux_refonte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `animaux_refonte` DEFAULT CHARACTER SET utf8 ;
USE `animaux_refonte` ;

-- -----------------------------------------------------
-- Table `animaux_refonte`.`Statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`Statut` (
  `id_statut` INT NOT NULL AUTO_INCREMENT,
  `libelle_statut` VARCHAR(45) NOT NULL,
  `description_statut` LONGTEXT NULL,
  PRIMARY KEY (`id_statut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`Animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `nom_animal` VARCHAR(45) NOT NULL,
  `type_animal` ENUM("chien", "chat") NOT NULL,
  `puce` INT NULL,
  `sexe` TINYINT NOT NULL,
  `ami_chien` ENUM("oui", "non", "N/A") NULL,
  `ami_chat` ENUM("oui", "non", "N/A") NULL,
  `ami_enfant` ENUM("oui", "non", "N/A") NULL,
  `description_animal` LONGTEXT NULL,
  `adoption_description_animal` LONGTEXT NULL,
  `localisation_description_animal` LONGTEXT NULL,
  `engagement_description_animal` LONGTEXT NULL,
  `id_statut` INT NOT NULL,
  PRIMARY KEY (`id_animal`),
  CONSTRAINT `fk_Animal_Statut`
    FOREIGN KEY (`id_statut`)
    REFERENCES `animaux_refonte`.`Statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`Caractere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`Caractere` (
  `id_caractere` INT NOT NULL AUTO_INCREMENT,
  `libelle_caractere` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_caractere`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`dispose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`dispose` (
  `id_caractere` INT NOT NULL,
  `id_animal` INT NOT NULL,
  PRIMARY KEY (`id_caractere`, `id_animal`),
  CONSTRAINT `fk_caractere_has_Animal_caractere1`
    FOREIGN KEY (`id_caractere`)
    REFERENCES `animaux_refonte`.`Caractere` (`id_caractere`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_caractere_has_Animal_Animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `animaux_refonte`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`Image` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `libelle_image` VARCHAR(45) NOT NULL,
  `url_image` VARCHAR(100) NOT NULL,
  `description_image` LONGTEXT NULL,
  PRIMARY KEY (`id_image`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`Actualite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`Actualite` (
  `id_actualite` INT NOT NULL AUTO_INCREMENT,
  `libelle_actualite` VARCHAR(45) NOT NULL,
  `date_publication_actualite` DATE NOT NULL,
  `type_actualite` ENUM("News", "Action", "Event") NULL,
  `id_image` INT NOT NULL,
  PRIMARY KEY (`id_actualite`, `id_image`),
  CONSTRAINT `fk_actualite_image1`
    FOREIGN KEY (`id_image`)
    REFERENCES `animaux_refonte`.`Image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`contient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`contient` (
  `id_animal` INT NOT NULL,
  `id_image` INT NOT NULL,
  PRIMARY KEY (`id_animal`, `id_image`),
  CONSTRAINT `fk_animal_has_image_animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `animaux_refonte`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_image_image1`
    FOREIGN KEY (`id_image`)
    REFERENCES `animaux_refonte`.`Image` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `animaux_refonte`.`associe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animaux_refonte`.`associe` (
  `id_animal` INT NOT NULL,
  `id_actualite` INT NOT NULL,
  PRIMARY KEY (`id_animal`, `id_actualite`),
  CONSTRAINT `fk_animal_has_actualite_animal1`
    FOREIGN KEY (`id_animal`)
    REFERENCES `animaux_refonte`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_has_actualite_actualite1`
    FOREIGN KEY (`id_actualite`)
    REFERENCES `animaux_refonte`.`Actualite` (`id_actualite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
